### ISSUE TITLE
Add a feature that allows copying attributes from entity to span/metric/log/

### ISSUE THREAD

**Issue by svrnm** [cisco-open/test-telemetry-generator#54]
In the signal (trace, metric, logs) definition it would be great to have the capability to copy from attributes of the reporting resource/entity. For example, if my reporting resource has an attribute `service.name` I would like use that in the definition of a span, e.g.

 in trace/metric/logs definition is there a way to copy from attributes of the reporting resource, e.g. my reporting resource has a service.name and I want to use that in an attribute of the http request, e.g. something like `http.url: ‘“/api/v1”.concat(VALUEOFTHATATTRIBUTE)’`

```yaml
  - name: 'fromResourceAttributes("service.name").concat("-checkout")'
    spanKind: SPAN_KIND_SERVER
    reportingResource: frontend_instance
    attributes:
      http.method: '"POST"'
      http.url: 'fromResourceAttributes("service.name").concat("/checkout")'
    childSpans: ["doCheckout"]
```
